# Generated by Django 5.2.1 on 2026-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagemedia_videomedia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchindex',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='field_type',
            field=models.CharField(choices=[('title', 'Title'), ('content', 'Content'), ('meta', 'Metadata'), ('media_alt', 'Media Alt Text')], default='content', max_length=20),
        ),
        migrations.AddField(
            model_name='searchindex',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterUniqueTogether(
            name='searchindex',
            unique_together={('word', 'page', 'field_type')},
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['word', 'weight'], name='core_search_word_15b93f_idx'),
        ),
    ]
